Repository BuildForSDGCohort2/Team-185-backend, pull requests merged in 2020-09, with the labels that each got.

#7 Node.JS and Express Setup
  .gitignore
  Procfile
  README.md
  app.js
  package-lock.json
  package.json
  server.js
Labels: Express, Heroku, MongoDB, Node.JS, enhancement

#4 Create LICENSE
  LICENSE
Labels: documentation, good first issue

#10 mongodb setup using mongoose
  .gitignore
  app.js
  controllers/users.js
  db.js
  models/users.js
  package-lock.json
  package.json
  routes/users.js
Labels: Heroku, MongoDB

#12 Big fixes on mongo db integration
  app.js
  db.js
Labels: Express, MongoDB, Node.JS

#13 Backend Revamp - Models, Routes and Static Assets
  .env
  README.md
  app.js
  db.js
  models/item.js
  models/users.js
  package-lock.json
  package.json
  public/index.html
  routes/items.js
  server.js
Labels: Heroku, MongoDB, Node.JS, setup

#17 Authentication, and Validation
  app.js
  config/default.json
  controllers/users.js
  db.js
  middleware/auth.js
  models/userModel.js
  models/users.js
  package-lock.json
  package.json
  routes/api/auth.js
  routes/api/income_items.js
  routes/api/users.js
  routes/users.js
Labels: JWT, Middleware, Token, Validation
